# Contains the configuration for Starship prompt
add_newline = true

[character] # the name of the module we are configuring is 'character'
success_symbol = '[❯](bold #d97757)'
error_symbol = '[❯](bold #d86464)'

## First param
[username]
format = "[$user]($style)"
style_user = "#d97757"
style_root = "#f29b79"
show_always = true

## Second param
[hostname]
disabled = false
format = "[@$hostname]($style) "
# style = "bold dimmed red"
style = "#a8a096"
trim_at = "-"
ssh_only = false

[directory]
read_only = "🔒"
# truncation_length = 3 
# truncation_symbol = "…"
truncate_to_repo = true
# style = "#d97757"
style = "bold #f29b79"
# style = "bold white"

[git_branch]
always_show_remote = false
symbol = ' '
# truncation_length = 4
# truncation_symbol = ''
style = 'bold #d97757'
# ignore_branches = ['master', 'main']

[git_status]
style = "bold #d86464"
disabled = false

[git_metrics]
added_style = "#7aa89f"
deleted_style = "#d86464"
disabled = false


[python]
format = 'via [${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'
version_format = "${raw}" 
symbol = " "
style = 'bold #d97757'
# pyenv_version_name = true
# pyenv_prefix = "pyenv "

# Last param in the first line/row
# [cmd_duration]
# min_time = 1
# format = "took [$duration]($style)"
# disabled = false

[docker_context]
format = 'via [🐋 $context](blue bold) '

[lua]
format = 'via [ $version]($style) '
style = 'bold #d97757'


# Disable the package module, hiding it from the prompt completely
[package]
disabled = true


[aws]
disabled = true
# format = 'on [$symbol($profile )(\($region\) )]($style)'
# style = 'bold blue'
# symbol = '🅰 '
# [aws.region_aliases]
# ap-southeast-2 = 'au'
# us-east-1 = 'va'
# [aws.profile_aliases]
# CompanyGroupFrobozzOnCallAccess = 'Frobozz'

[localip]
ssh_only = true
disabled = false

