#!/usr/bin/env node

import { fetchTranscript, listLanguages } from "youtube-transcript-plus";

const DEFAULT_MAX_CHARS = 30_000;
const REQUEST_TIMEOUT_MS = 30_000;

function usage() {
  console.error("Usage: transcript.js <youtube-url-or-id> [--lang <code>] [--languages] [--max-chars <n>]");
}

function parseArgs(argv) {
  const positional = [];
  let lang;
  let languages = false;
  let maxChars = DEFAULT_MAX_CHARS;

  for (let i = 0; i < argv.length; i++) {
    const arg = argv[i];
    if (arg === "--lang") {
      lang = argv[++i];
      if (!lang) throw new Error("--lang requires a language code");
    } else if (arg === "--languages") {
      languages = true;
    } else if (arg === "--max-chars") {
      const value = Number(argv[++i]);
      if (!Number.isInteger(value) || value < 1 || value > 50_000) {
        throw new Error("--max-chars must be an integer between 1 and 50000");
      }
      maxChars = value;
    } else if (arg.startsWith("--")) {
      throw new Error(`Unknown option: ${arg}`);
    } else {
      positional.push(arg);
    }
  }

  if (positional.length !== 1) throw new Error("Provide exactly one YouTube URL or video ID");
  return { input: positional[0], lang, languages, maxChars };
}

function normalizeVideoId(input) {
  const trimmed = input.trim();
  if (/^[A-Za-z0-9_-]{11}$/.test(trimmed)) return trimmed;

  let url;
  try {
    url = new URL(trimmed);
  } catch {
    throw new Error("Invalid YouTube URL or 11-character video ID");
  }

  const host = url.hostname.replace(/^www\./, "").toLowerCase();
  let id;
  if (host === "youtu.be") {
    id = url.pathname.split("/").filter(Boolean)[0];
  } else if (host === "youtube.com" || host.endsWith(".youtube.com")) {
    if (url.pathname === "/watch") id = url.searchParams.get("v");
    else {
      const parts = url.pathname.split("/").filter(Boolean);
      if (["shorts", "live", "embed", "v"].includes(parts[0])) id = parts[1];
    }
  }

  if (!id || !/^[A-Za-z0-9_-]{11}$/.test(id)) {
    throw new Error("Could not find a valid video ID in the YouTube URL");
  }
  return id;
}

function decodeHtmlEntities(value) {
  const named = { amp: "&", apos: "'", quot: "\"", lt: "<", gt: ">" };
  return value
    .replace(/&#x([0-9a-f]+);/gi, (_match, hex) => String.fromCodePoint(Number.parseInt(hex, 16)))
    .replace(/&#(\d+);/g, (_match, decimal) => String.fromCodePoint(Number.parseInt(decimal, 10)))
    .replace(/&(amp|apos|quot|lt|gt);/gi, (_match, name) => named[name.toLowerCase()]);
}

function formatTimestamp(rawOffset) {
  const offset = Number(rawOffset);
  const seconds = Number.isFinite(offset) ? Math.floor(offset > 10_000 ? offset / 1000 : offset) : 0;
  const hours = Math.floor(seconds / 3600);
  const minutes = Math.floor((seconds % 3600) / 60);
  const remainder = seconds % 60;
  return hours > 0
    ? `${hours}:${String(minutes).padStart(2, "0")}:${String(remainder).padStart(2, "0")}`
    : `${minutes}:${String(remainder).padStart(2, "0")}`;
}

function formatError(error) {
  const name = error instanceof Error ? error.name : "";
  const message = error instanceof Error ? error.message : String(error);
  if (/Disabled|NotAvailable|Unavailable/i.test(name + message)) {
    return `Captions are unavailable for this video. ${message}`;
  }
  if (/TooManyRequest|429|rate.limit/i.test(name + message)) {
    return `YouTube rate-limited caption retrieval. Try again later. ${message}`;
  }
  return `Transcript retrieval failed: ${message}`;
}

try {
  const { input, lang, languages, maxChars } = parseArgs(process.argv.slice(2));
  const videoId = normalizeVideoId(input);
  const controller = new AbortController();
  const timeout = setTimeout(() => controller.abort(), REQUEST_TIMEOUT_MS);

  try {
    const options = { ...(lang ? { lang } : {}), retries: 2, retryDelay: 750, signal: controller.signal };
    if (languages) {
      const available = await listLanguages(videoId, options);
      if (available.length === 0) {
        console.log("No caption languages are available.");
      } else {
        for (const item of available) {
          console.log(`${item.languageCode}\t${item.languageName}\t${item.isAutoGenerated ? "auto-generated" : "manual"}`);
        }
      }
    } else {
      const segments = await fetchTranscript(videoId, options);
      let printed = 0;
      let omitted = 0;
      for (const segment of segments) {
        const text = decodeHtmlEntities(String(segment.text ?? "")).replace(/\s+/g, " ").trim();
        if (!text) continue;
        const line = `[${formatTimestamp(segment.offset)}] ${text}`;
        if (printed + line.length + 1 > maxChars) {
          omitted++;
          continue;
        }
        console.log(line);
        printed += line.length + 1;
      }
      if (omitted > 0) {
        console.log(`\n[Transcript truncated after ${printed} characters; ${omitted} later segment(s) omitted. Re-run with --max-chars up to 50000 if needed.]`);
      }
    }
  } finally {
    clearTimeout(timeout);
  }
} catch (error) {
  console.error(formatError(error));
  process.exitCode = 1;
}
